version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      opa:
        condition: service_healthy
    networks:
      - opa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/public-data"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  opa:
    build: ./opa
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--addr"
      - ":8181"
      - "/policies"
    volumes:
      - ./policies:/policies
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - opa-network

networks:
  opa-network:
    driver: bridge 